### ISSUE TITLE
About the validation performance.

### ISSUE THREAD

**Issue by YannnWanggg** [Mercerai/PFGS#2]
Great work! I am curious about the validation performance on ScanNet. I noticed that in your code, even during validation, only one random image is selected for each scene to calculate metrics. Is my understanding correct? What's more, are the results reported in the paper obtained similarly?

**Comment by Mercerai** [comment]
Yes. We only randomly select a subset of all eval scenes to speed up the running of the code demo. But to obtain faithful final results, one should average the metrics across all test scenes.
