### ISSUE TITLE
Can you provide the images.txt in scannet dataset?

### ISSUE THREAD

**Issue by Sugar55888** [Mercerai/PFGS#3]
Thank you!

**Comment by Zerory1** [comment]
You can get it from Scannet (https://github.com/ScanNet/ScanNet)

**Comment by ERGOWHO** [comment]
Hi， @Sugar55888  I also ran into the same issue, the images.txt is required by PFGS and not provided by scannet's download and read code.

So I have to manually add the images.txt like this:
0 color/0.jpg
1 color/1.jpg
2 color/2.jpg
3 color/3.jpg
4 color/4.jpg
5 color/5.jpg
6 color/6.jpg
7 color/7.jpg
8 color/8.jpg
9 color/9.jpg

。。。
5567 color/5567.jpg
5568 color/5568.jpg
5569 color/5569.jpg
5570 color/5570.jpg
5571 color/5571.jpg
5572 color/5572.jpg
5573 color/5573.jpg
5574 color/5574.jpg
5575 color/5575.jpg
5576 color/5576.jpg
5577 color/5577.jpg
