### ISSUE TITLE
problem of installation of submodules/diff-gaussian-rasterization

### ISSUE THREAD

**Issue by daiguangzhao** [Mercerai/PFGS#4]
Thanks to the authors for contributing such great work to the community.  When I install the “submodules/diff-gaussian-rasterization” package it always fails, even if I use the conda recommended environment and CUDA version. Can I use the package in (https://github.com/ShijieZhou-UCLA/feature-3dgs/tree/main/submodules/diff-gaussian-rasterization-feature) instead? I modified the number of channels in "config.h" in diff-gaussian-rasterization-feature to 16 to keep it the same as PFGS.
![4afff20229131d554156d36079a6df6](https://github.com/user-attachments/assets/88b03155-7de0-47a4-9850-b527a248e92e)
![ba73082b53b042e29b361de6db33be7](https://github.com/user-attachments/assets/bec54806-694b-4c94-9add-1304b0354af7)

**Comment by Mercerai** [comment]
Hi, we fixed a bug in the backward function which might cause an error for some machines, please ignore the above answer. it is noted that you have to install the rasterization from this repo, the original feature-gs might not be supported by our method.

**Comment by daiguangzhao** [comment]
> Hi, we fixed a bug in the backward function which might cause an error for some machines, please ignore the above answer. it is noted that you have to install the rasterization from this repo, the original feature-gs might not be supported by our method.

Thank you~ happy new year
